version: "3.7"


services:
  nginx:
    image: nginx:mainline
    container_name: teste-nginx
    restart: always
    ports:
      - 8081:8081
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./hot-reload.sh:/root/hot-reload.sh:rw"
    command: sh /root/hot-reload.sh
