version: "3.7"


services:
  nginx:
    image: nginx:1.17.10-alpine
    container_name: nginx-lab
    restart: always
    command: sh /root/nginx-watch.sh
    ports:
      - 8081:8081
    volumes:
      - "./nginx-watch.sh:/root/nginx-watch.sh"
      - "./nginx-env/config/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx-env/config/conf.d:/etc/nginx/conf.d/"
      - "./nginx-env/logs:/var/log/nginx/"
